#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - rabbitmq-server
    - python-swiftclient

runcmd:
    - sudo git clone https://github.com/ekling/lab3.2.git /home/ubuntu/lab3.2
    - cd /home/ubuntu/lab3.2
    - sudo pip install -r requirements.txt
    - sudo pip install flower
    - rabbitmqctl add_user worker pw
    - rabbitmqctl add_vhost host
    - rabbitmqctl set_permissions -p host worker ".*" ".*" ".*"
    - export "0.0.0.0"
    - sudo -H -u ubuntu bash -c "python controller.py &"
    - sudo -H -u ubuntu bash -c "celery flower -A parse &"
