#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - rabbitmq-server
    - python-swiftclient

runcmd:
    - git clone https://github.com/ekling/lab3.2.git /home/ubuntu/lab3.2
    - cd /home/ubuntu/lab3.2
    - git checkout part2
    - pip install -r requirements.txt
    - brokerip
    - sudo -H -u ubuntu bash -c "celery worker -A parse &"
