#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - rabbitmq-server
    - python-swiftclient

runcmd:
    - git clone https://github.com/ekling/lab3.2.git /home/ubuntu/lab3.2
    - cd /home/ubuntu/lab3.2
    - pip install -r requirements.txt
    - export C_FORCE_ROOT="true"
    - export BROKER_IP="130.238.29.36"
    - celery worker -A parse &
